import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-theme="light">
        <div id="fb-root" />
        {/* <script src="https://connect.facebook.net/en_US/sdk.js"></script> */}
        
        {children}
      </body>
    </html>
  )
}
