version: '3'
services:
  nocodb:
    image: nocodb/nocodb:latest
    volumes:
      - ./nocodb:/usr/src/app/data
    ports:
      - 8083:8083
  web:
    build:
        context: .
    ports:
      - 8081:8081
    volumes:
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
  nitro:
    build:
        context: ./nitro
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY
  next:
    build:
        context: ./nextjs-docker
    ports:
      - 3001:3001
    environment:
      - OPENAI_API_KEY
      - INNGEST_SIGNING_KEY
      - INNGEST_EVENT_KEY
      - INNGEST_SERVE_PATH