version: '3'
services:
  web:
    build:
        context: .
    ports:
      - 8081:8081
    volumes:
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
  nitro:
    build:
        context: ./nitro
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY