services:
  web:
    build:
        context: .
    ports:
      - 8081:8081
    volumes:
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
  next:
    build:
        context: ./nextjs-docker
    ports:
      - 3001:3001
    environment:
      - OPENAI_API_KEY
      - INNGEST_SIGNING_KEY
      - INNGEST_EVENT_KEY
      - INNGEST_SERVE_PATH
      - NODE_ENV=production
      - WA_PHONE_NUMBER_ID
      - CLOUD_API_ACCESS_TOKEN
      - CLOUD_API_VERSION=v16.0